version: '3'
networks:
   profile-network:
       external: true
       name: 'mongo-network'
services:
  app:
    container_name: profileapp
    image: profileapp:1.0
    build: .      # Location of Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_PASS=secret
      - MONGO_HOST=database 
    networks:
       - profile-network
    depends_on:
      - database

  database:
    container_name: database
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
       - profile-network
    volumes:    # NEW
          - ./data:/db/data 

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always # fixes MongoNetworkError caused by database not being ready when mongo-express starts.
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_database_ADMINUSERNAME=admin
      - ME_CONFIG_database_ADMINPASSWORD=secret
      - ME_CONFIG_database_SERVER=database
    networks:
       - profile-network
    depends_on:
      - database